Fix RUNZSH and unnatended mode omz_install

diff --git a/scripts/provision_first_run b/scripts/provision_first_run
--- a/scripts/provision_first_run
+++ b/scripts/provision_first_run
@@ -5,15 +5,13 @@ source ./scripts/wait_process.sh
 
 STATUSFILE=~/.local/share/.dotfiles/status
 
-# arch="$(uname -m)"
 distro="$(lsb_release -i -s)"
-# dist_release="$(lsb_release -r -s)"
 
 function check_bin () {
     if [ -x "$(which $1)" ]; then
         return 0
     else
-        printf '^s not found in $PATH.\n' ${1^} >&2 
+        printf '%s not found in $PATH.\n' ${1^} >&2 
         return 1
     fi
     
@@ -26,11 +24,13 @@ function install_omz () {
         return 0
     fi
 
-    RUNZSH=no
-    sh -c "$(curl -fsSL \
-        https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" \
-        --unattended
     
+     
+    
+    wget -q "https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh"\
+        -O /tmp/install.sh     
+    CHSH=yes RUNZSH=no bash /tmp/install.sh 
+    rm /tmp/install.sh
     return 0
 }
 
@@ -119,6 +119,7 @@ function main () {
         install_packages_ubuntu
     fi
     
+    setup_git_username
     install_omz
 
     mkdir -p ~/.local/share/.dotfiles/
