Fix run_dotbot, git update from remote

diff --git a/files/zshrc b/files/zshrc
--- a/files/zshrc
+++ b/files/zshrc
@@ -8,13 +8,13 @@ export ZSH="$HOME/.oh-my-zsh"
 # load a random theme each time oh-my-zsh is loaded, in which case,
 # to know which specific one was loaded, run: echo $RANDOM_THEME
 # See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
-ZSH_THEME="robbyrussell"
+ZSH_THEME="random"
 
 # Set list of themes to pick from when loading at random
 # Setting this variable when ZSH_THEME=random will cause zsh to load
 # a theme from this variable instead of looking in $ZSH/themes/
 # If set to an empty array, this variable will have no effect.
-# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )
+ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "jnrowe" )
 
 # Uncomment the following line to use case-sensitive completion.
 CASE_SENSITIVE="true"
@@ -84,9 +84,20 @@ plugins=(
 source $ZSH/oh-my-zsh.sh
 
 # User configuration
-if [ -r "~/.config/aliases" ]; then
-    source ~/.config/aliases
-fi
+source_scripts=(
+  "${HOME}/.config/aliases"
+  "${HOME}/.config/functions"
+)
+
+for source_script in "${source_scripts[@]}"; do
+  file ${source_script}
+  if [ ! -r "${source_script}" ] && [ ! -h "${source_script}" ] ; then
+    printf 'Cannot load file %s\n' "${source_script}" >&2
+    continue
+  fi
+
+  source "${source_scripts}"
+done 
 
 # export MANPATH="/usr/local/man:$MANPATH"
 
diff --git a/scripts/provision_first_run b/scripts/provision_first_run
--- a/scripts/provision_first_run
+++ b/scripts/provision_first_run
@@ -4,9 +4,21 @@ source ./scripts/wait_process.sh
 
 
 STATUSFILE=~/.local/share/.dotfiles/status
+
 # arch="$(uname -m)"
 distro="$(lsb_release -i -s)"
 # dist_release="$(lsb_release -r -s)"
+
+function check_bin () {
+    if [ -x "$(which $1)" ]; then
+        return 0
+    else
+        printf '^s not found in $PATH.\n' ${1^} >&2 
+        return 1
+    fi
+    
+}
+
 
 function install_omz () {
     ### Download from omz repo
@@ -14,6 +26,7 @@ function install_omz () {
         return 0
     fi
 
+    RUNZSH=no
     sh -c "$(curl -fsSL \
         https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" \
         --unattended
@@ -21,6 +34,16 @@ function install_omz () {
     return 0
 }
 
+function setup_git_username(){
+    if ! check_bin git; then 
+        exit 2
+    fi
+
+    printf 'Configuring Git...\n' >&2
+    git config --global user.email "${USER_EMAIL}"
+    git config --global user.name "${USER_NAME}"
+
+}
 
 function install_packages_ubuntu (){
 
@@ -38,8 +61,7 @@ function install_packages_ubuntu (){
     sudo apt install -qq -y "${ubuntu_pkg_list[@]}" >/dev/null 2>&1 & 
     wait_process $! "Installing packages"
 
-    sudo pip install -U pip
-    sudo pip install dotbot
+    sudo pip install -U pip dotbot
 
 }
 
@@ -71,9 +93,12 @@ function check_run_date (){
 }
 
 function run_dotbot () {
-    if [ -x "${DOTBOT_BIN}" ]; then 
-        exec
+    if ! check_bin "${DOTBOT_BIN}"; then 
+        exit 2
+    fi
+
     "${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" 
+    return 0
 }
 
 
@@ -96,18 +121,16 @@ function main () {
     
     install_omz
 
-    mkdir ~/.local/share/.dotfiles/
+    mkdir -p ~/.local/share/.dotfiles/
     date +"@%s" > ~/.local/share/.dotfiles/status
 
     run_dotbot 
 
     ### Running zsh if everything is OK
-    zsh_path="$(which zsh)"
-    if [ -x "${zsh_path}" ]; then
+    if check_bin zsh; then
         printf 'Iniciando ZSH:%s\n' "${zsh_path}"
         ${zsh_path}
     fi
-
 
 }
 
